version: '3.8'
services: 
    service-ai:
        build:
            context: ./ai
        env_file:
            - .env
        volumes: 
            - ./ai/server:/app/server
            - ./ai/logs:/app/logs
        ports:
            - "9001:9001"
    service-binance:
        build:
            context: ./api
        env_file:
            - .env
            - .env_key
        volumes:
            - ./api/src:/app/src
        ports: 
            - "9000:9000"
    frontend:
        build:
            context: ./front
        env_file:
            - .env
        volumes:
            - ./front/src:/app/src
        ports:
            - "80:3000"
    database-mysql:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_ROOT_PASSWORD=password
        ports:
            - 0.0.0.0:7200:3306
        volumes:
            - ./database/cryptobot_db.sql:/docker-entrypoint-initdb.d/sample.sql
    service-db:
        build:
            context: ./service_db
        env_file:
            - .env
        volumes:
            - ./service_db/src:/app/src
        ports: 
            - "9002:9002"